# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(752, 728)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(333, 0, 40, 731))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 350, 524))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_4 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.rx_label_21 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_21.setFrameShape(QtGui.QFrame.Panel)
        self.rx_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_21.setObjectName(_fromUtf8("rx_label_21"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.rx_label_21)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 1, 2, 1, 1)
        self.rx_label_22 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_22.setObjectName(_fromUtf8("rx_label_22"))
        self.gridLayout_3.addWidget(self.rx_label_22, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.rx_label_23 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_23.setObjectName(_fromUtf8("rx_label_23"))
        self.gridLayout_4.addWidget(self.rx_label_23, 0, 0, 1, 1)
        self.lineEdit_tx_data_DCin = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_data_DCin.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_data_DCin.setObjectName(_fromUtf8("lineEdit_tx_data_DCin"))
        self.gridLayout_4.addWidget(self.lineEdit_tx_data_DCin, 0, 1, 1, 1)
        self.rx_label_25 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_25.setObjectName(_fromUtf8("rx_label_25"))
        self.gridLayout_4.addWidget(self.rx_label_25, 1, 0, 1, 1)
        self.lineEdit_tx_data_AC_dem = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_data_AC_dem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_data_AC_dem.setObjectName(_fromUtf8("lineEdit_tx_data_AC_dem"))
        self.gridLayout_4.addWidget(self.lineEdit_tx_data_AC_dem, 1, 1, 1, 1)
        self.rx_label_26 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_26.setObjectName(_fromUtf8("rx_label_26"))
        self.gridLayout_4.addWidget(self.rx_label_26, 2, 0, 1, 1)
        self.lineEdit_tx_data_Lin = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_data_Lin.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_data_Lin.setObjectName(_fromUtf8("lineEdit_tx_data_Lin"))
        self.gridLayout_4.addWidget(self.lineEdit_tx_data_Lin, 2, 1, 1, 1)
        self.rx_label_28 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_28.setObjectName(_fromUtf8("rx_label_28"))
        self.gridLayout_4.addWidget(self.rx_label_28, 3, 0, 1, 1)
        self.lineEdit_tx_data_Ttxboard = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_data_Ttxboard.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_data_Ttxboard.setObjectName(_fromUtf8("lineEdit_tx_data_Ttxboard"))
        self.gridLayout_4.addWidget(self.lineEdit_tx_data_Ttxboard, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.rx_label_29 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_29.setObjectName(_fromUtf8("rx_label_29"))
        self.gridLayout_3.addWidget(self.rx_label_29, 2, 0, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.checkBox_tx_state_overVsens = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_overVsens.setObjectName(_fromUtf8("checkBox_tx_state_overVsens"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_tx_state_overVsens)
        self.checkBox_tx_state_underVsens = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_underVsens.setObjectName(_fromUtf8("checkBox_tx_state_underVsens"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBox_tx_state_underVsens)
        self.checkBox_tx_state_overACdem = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_overACdem.setObjectName(_fromUtf8("checkBox_tx_state_overACdem"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBox_tx_state_overACdem)
        self.checkBox_tx_state_underACdem = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_underACdem.setObjectName(_fromUtf8("checkBox_tx_state_underACdem"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkBox_tx_state_underACdem)
        self.checkBox_tx_state_lowIsens = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_lowIsens.setObjectName(_fromUtf8("checkBox_tx_state_lowIsens"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBox_tx_state_lowIsens)
        self.checkBox_tx_state_overTsens = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_overTsens.setObjectName(_fromUtf8("checkBox_tx_state_overTsens"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBox_tx_state_overTsens)
        self.checkBox_tx_state_underTsens = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_tx_state_underTsens.setObjectName(_fromUtf8("checkBox_tx_state_underTsens"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBox_tx_state_underTsens)
        self.gridLayout_3.addLayout(self.formLayout_5, 2, 2, 1, 1)
        self.rx_label_30 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_30.setObjectName(_fromUtf8("rx_label_30"))
        self.gridLayout_3.addWidget(self.rx_label_30, 4, 0, 1, 1)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.rx_label_31 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_31.setObjectName(_fromUtf8("rx_label_31"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.rx_label_31)
        self.lineEdit_tx_thd_overVsens = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_overVsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_overVsens.setObjectName(_fromUtf8("lineEdit_tx_thd_overVsens"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_overVsens)
        self.rx_label_33 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_33.setObjectName(_fromUtf8("rx_label_33"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.rx_label_33)
        self.lineEdit_tx_thd_overAC_dem = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_overAC_dem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_overAC_dem.setObjectName(_fromUtf8("lineEdit_tx_thd_overAC_dem"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_overAC_dem)
        self.rx_label_34 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_34.setObjectName(_fromUtf8("rx_label_34"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.rx_label_34)
        self.lineEdit_tx_thd_underVsens = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_underVsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_underVsens.setObjectName(_fromUtf8("lineEdit_tx_thd_underVsens"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_underVsens)
        self.rx_label_36 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_36.setObjectName(_fromUtf8("rx_label_36"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.rx_label_36)
        self.lineEdit_tx_thd_underAC_dem = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_underAC_dem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_underAC_dem.setObjectName(_fromUtf8("lineEdit_tx_thd_underAC_dem"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_underAC_dem)
        self.rx_label_37 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_37.setObjectName(_fromUtf8("rx_label_37"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.rx_label_37)
        self.lineEdit_tx_thd_lowIsens = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_lowIsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_lowIsens.setObjectName(_fromUtf8("lineEdit_tx_thd_lowIsens"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_lowIsens)
        self.rx_label_39 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_39.setObjectName(_fromUtf8("rx_label_39"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.rx_label_39)
        self.lineEdit_tx_thd_overTsens = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_overTsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_overTsens.setObjectName(_fromUtf8("lineEdit_tx_thd_overTsens"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_overTsens)
        self.rx_label_40 = QtGui.QLabel(self.layoutWidget)
        self.rx_label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_40.setObjectName(_fromUtf8("rx_label_40"))
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.LabelRole, self.rx_label_40)
        self.lineEdit_tx_thd_underTsens = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_tx_thd_underTsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tx_thd_underTsens.setObjectName(_fromUtf8("lineEdit_tx_thd_underTsens"))
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_tx_thd_underTsens)
        self.gridLayout_3.addLayout(self.formLayout_6, 4, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 1, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_3.addWidget(self.line_7, 3, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 3, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.layoutWidget)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_3.addWidget(self.line_10, 0, 1, 1, 1)
        self.line_11 = QtGui.QFrame(self.layoutWidget)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_3.addWidget(self.line_11, 2, 1, 1, 1)
        self.line_12 = QtGui.QFrame(self.layoutWidget)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_3.addWidget(self.line_12, 4, 1, 1, 1)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.LabelRole, self.gridLayout_3)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(356, 0, 385, 715))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.rx_label = QtGui.QLabel(self.layoutWidget1)
        self.rx_label.setFrameShape(QtGui.QFrame.Panel)
        self.rx_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label.setObjectName(_fromUtf8("rx_label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.rx_label)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line_9 = QtGui.QFrame(self.layoutWidget1)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_2.addWidget(self.line_9, 3, 2, 1, 1)
        self.rx_label_8 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_8.setObjectName(_fromUtf8("rx_label_8"))
        self.gridLayout_2.addWidget(self.rx_label_8, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rx_label_2 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_2.setObjectName(_fromUtf8("rx_label_2"))
        self.gridLayout.addWidget(self.rx_label_2, 0, 0, 1, 1)
        self.lineEdit_data_Vrect = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_data_Vrect.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_Vrect.setObjectName(_fromUtf8("lineEdit_data_Vrect"))
        self.gridLayout.addWidget(self.lineEdit_data_Vrect, 0, 1, 1, 1)
        self.rx_label_3 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_3.setObjectName(_fromUtf8("rx_label_3"))
        self.gridLayout.addWidget(self.rx_label_3, 1, 0, 1, 1)
        self.lineEdit_data_Vcha = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_data_Vcha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_Vcha.setObjectName(_fromUtf8("lineEdit_data_Vcha"))
        self.gridLayout.addWidget(self.lineEdit_data_Vcha, 1, 1, 1, 1)
        self.rx_label_4 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_4.setObjectName(_fromUtf8("rx_label_4"))
        self.gridLayout.addWidget(self.rx_label_4, 2, 0, 1, 1)
        self.lineEdit_data_Fsk_dem = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_data_Fsk_dem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_Fsk_dem.setObjectName(_fromUtf8("lineEdit_data_Fsk_dem"))
        self.gridLayout.addWidget(self.lineEdit_data_Fsk_dem, 2, 1, 1, 1)
        self.rx_label_6 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_6.setObjectName(_fromUtf8("rx_label_6"))
        self.gridLayout.addWidget(self.rx_label_6, 3, 0, 1, 1)
        self.lineEdit_data_Irect = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_data_Irect.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_Irect.setObjectName(_fromUtf8("lineEdit_data_Irect"))
        self.gridLayout.addWidget(self.lineEdit_data_Irect, 3, 1, 1, 1)
        self.rx_label_7 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_7.setObjectName(_fromUtf8("rx_label_7"))
        self.gridLayout.addWidget(self.rx_label_7, 4, 0, 1, 1)
        self.lineEdit_data_Icha = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_data_Icha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_Icha.setObjectName(_fromUtf8("lineEdit_data_Icha"))
        self.gridLayout.addWidget(self.lineEdit_data_Icha, 4, 1, 1, 1)
        self.rx_label_5 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_5.setObjectName(_fromUtf8("rx_label_5"))
        self.gridLayout.addWidget(self.rx_label_5, 5, 0, 1, 1)
        self.lineEdit_data_Treboard = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_data_Treboard.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_Treboard.setObjectName(_fromUtf8("lineEdit_data_Treboard"))
        self.gridLayout.addWidget(self.lineEdit_data_Treboard, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.rx_label_9 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_9.setObjectName(_fromUtf8("rx_label_9"))
        self.gridLayout_2.addWidget(self.rx_label_9, 2, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBox_state_overVsens = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_overVsens.setObjectName(_fromUtf8("checkBox_state_overVsens"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_state_overVsens)
        self.checkBox_state_underVsens = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_underVsens.setObjectName(_fromUtf8("checkBox_state_underVsens"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.checkBox_state_underVsens)
        self.checkBox_state_overVsensCHA = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_overVsensCHA.setObjectName(_fromUtf8("checkBox_state_overVsensCHA"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBox_state_overVsensCHA)
        self.checkBox_state_underVsensCHA = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_underVsensCHA.setObjectName(_fromUtf8("checkBox_state_underVsensCHA"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkBox_state_underVsensCHA)
        self.checkBox_state_overFsk_dem = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_overFsk_dem.setObjectName(_fromUtf8("checkBox_state_overFsk_dem"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBox_state_overFsk_dem)
        self.checkBox_state_underFsk_dem = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_underFsk_dem.setObjectName(_fromUtf8("checkBox_state_underFsk_dem"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBox_state_underFsk_dem)
        self.checkBox_state_lowIsens = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_lowIsens.setObjectName(_fromUtf8("checkBox_state_lowIsens"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBox_state_lowIsens)
        self.checkBox_state_lowIsensCHA = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_lowIsensCHA.setObjectName(_fromUtf8("checkBox_state_lowIsensCHA"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBox_state_lowIsensCHA)
        self.checkBox_state_overTsens = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_overTsens.setObjectName(_fromUtf8("checkBox_state_overTsens"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBox_state_overTsens)
        self.checkBox_state_underTsens = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_state_underTsens.setObjectName(_fromUtf8("checkBox_state_underTsens"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBox_state_underTsens)
        self.gridLayout_2.addLayout(self.formLayout, 2, 2, 1, 1)
        self.rx_label_10 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_10.setObjectName(_fromUtf8("rx_label_10"))
        self.gridLayout_2.addWidget(self.rx_label_10, 4, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 3, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.rx_label_11 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_11.setObjectName(_fromUtf8("rx_label_11"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.rx_label_11)
        self.lineEdit_thd_overVsens = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_overVsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_overVsens.setObjectName(_fromUtf8("lineEdit_thd_overVsens"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_overVsens)
        self.rx_label_12 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rx_label_12.setObjectName(_fromUtf8("rx_label_12"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.rx_label_12)
        self.lineEdit_thd_overVsensCHA = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_overVsensCHA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_overVsensCHA.setObjectName(_fromUtf8("lineEdit_thd_overVsensCHA"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_overVsensCHA)
        self.rx_label_13 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_13.setObjectName(_fromUtf8("rx_label_13"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.rx_label_13)
        self.lineEdit_thd_overFsk_dem = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_overFsk_dem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_overFsk_dem.setObjectName(_fromUtf8("lineEdit_thd_overFsk_dem"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_overFsk_dem)
        self.rx_label_14 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_14.setObjectName(_fromUtf8("rx_label_14"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.rx_label_14)
        self.lineEdit_thd_underVsens = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_underVsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_underVsens.setObjectName(_fromUtf8("lineEdit_thd_underVsens"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_underVsens)
        self.rx_label_15 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_15.setObjectName(_fromUtf8("rx_label_15"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.rx_label_15)
        self.lineEdit_thd_underVsensCHA = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_underVsensCHA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_underVsensCHA.setObjectName(_fromUtf8("lineEdit_thd_underVsensCHA"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_underVsensCHA)
        self.rx_label_16 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_16.setObjectName(_fromUtf8("rx_label_16"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.rx_label_16)
        self.lineEdit_thd_underFsk_dem = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_underFsk_dem.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_underFsk_dem.setObjectName(_fromUtf8("lineEdit_thd_underFsk_dem"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_underFsk_dem)
        self.rx_label_20 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_20.setObjectName(_fromUtf8("rx_label_20"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.rx_label_20)
        self.lineEdit_thd_lowIsens = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_lowIsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_lowIsens.setObjectName(_fromUtf8("lineEdit_thd_lowIsens"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_lowIsens)
        self.rx_label_19 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_19.setObjectName(_fromUtf8("rx_label_19"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.rx_label_19)
        self.lineEdit_thd_lowIsensCHA = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_lowIsensCHA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_lowIsensCHA.setObjectName(_fromUtf8("lineEdit_thd_lowIsensCHA"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_lowIsensCHA)
        self.rx_label_18 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_18.setObjectName(_fromUtf8("rx_label_18"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.rx_label_18)
        self.lineEdit_thd_overTsens = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_overTsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_overTsens.setObjectName(_fromUtf8("lineEdit_thd_overTsens"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_overTsens)
        self.rx_label_17 = QtGui.QLabel(self.layoutWidget1)
        self.rx_label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.rx_label_17.setObjectName(_fromUtf8("rx_label_17"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.rx_label_17)
        self.lineEdit_thd_underTsens = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_thd_underTsens.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_thd_underTsens.setObjectName(_fromUtf8("lineEdit_thd_underTsens"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_thd_underTsens)
        self.gridLayout_2.addLayout(self.formLayout_2, 4, 2, 1, 1)
        self.line_8 = QtGui.QFrame(self.layoutWidget1)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_2.addWidget(self.line_8, 1, 2, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_13 = QtGui.QFrame(self.layoutWidget1)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_2.addWidget(self.line_13, 0, 1, 1, 1)
        self.line_14 = QtGui.QFrame(self.layoutWidget1)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_2.addWidget(self.line_14, 2, 1, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget1)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_2.addWidget(self.line_15, 4, 1, 1, 1)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.LabelRole, self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wireless Charge", None))
        self.rx_label_21.setText(_translate("MainWindow", "Tx", None))
        self.rx_label_22.setText(_translate("MainWindow", "Data", None))
        self.rx_label_23.setText(_translate("MainWindow", "DCin", None))
        self.lineEdit_tx_data_DCin.setText(_translate("MainWindow", "0", None))
        self.rx_label_25.setText(_translate("MainWindow", "AC_dem", None))
        self.lineEdit_tx_data_AC_dem.setText(_translate("MainWindow", "0", None))
        self.rx_label_26.setText(_translate("MainWindow", "Iin", None))
        self.lineEdit_tx_data_Lin.setText(_translate("MainWindow", "0", None))
        self.rx_label_28.setText(_translate("MainWindow", "Ttxboard", None))
        self.lineEdit_tx_data_Ttxboard.setText(_translate("MainWindow", "0", None))
        self.rx_label_29.setText(_translate("MainWindow", "State", None))
        self.checkBox_tx_state_overVsens.setText(_translate("MainWindow", "Over Vsens", None))
        self.checkBox_tx_state_underVsens.setText(_translate("MainWindow", "Under Vsens", None))
        self.checkBox_tx_state_overACdem.setText(_translate("MainWindow", "Over AC dem", None))
        self.checkBox_tx_state_underACdem.setText(_translate("MainWindow", "Under AC dem", None))
        self.checkBox_tx_state_lowIsens.setText(_translate("MainWindow", "Low Isens", None))
        self.checkBox_tx_state_overTsens.setText(_translate("MainWindow", "Over Tsens", None))
        self.checkBox_tx_state_underTsens.setText(_translate("MainWindow", "Under Tsens", None))
        self.rx_label_30.setText(_translate("MainWindow", "Threshold", None))
        self.rx_label_31.setText(_translate("MainWindow", "OverVsens", None))
        self.lineEdit_tx_thd_overVsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_33.setText(_translate("MainWindow", "OverAC_dem", None))
        self.lineEdit_tx_thd_overAC_dem.setText(_translate("MainWindow", "0", None))
        self.rx_label_34.setText(_translate("MainWindow", "UnderVsens", None))
        self.lineEdit_tx_thd_underVsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_36.setText(_translate("MainWindow", "UnderAC_dem", None))
        self.lineEdit_tx_thd_underAC_dem.setText(_translate("MainWindow", "0", None))
        self.rx_label_37.setText(_translate("MainWindow", "LowIsens", None))
        self.lineEdit_tx_thd_lowIsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_39.setText(_translate("MainWindow", "OverTsens", None))
        self.lineEdit_tx_thd_overTsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_40.setText(_translate("MainWindow", "UnserTsens", None))
        self.lineEdit_tx_thd_underTsens.setText(_translate("MainWindow", "0", None))
        self.rx_label.setText(_translate("MainWindow", "Rx", None))
        self.rx_label_8.setText(_translate("MainWindow", "Data", None))
        self.rx_label_2.setText(_translate("MainWindow", "Vrect", None))
        self.lineEdit_data_Vrect.setText(_translate("MainWindow", "0", None))
        self.rx_label_3.setText(_translate("MainWindow", "Vcha", None))
        self.lineEdit_data_Vcha.setText(_translate("MainWindow", "0", None))
        self.rx_label_4.setText(_translate("MainWindow", "Fsk_dem", None))
        self.lineEdit_data_Fsk_dem.setText(_translate("MainWindow", "0", None))
        self.rx_label_6.setText(_translate("MainWindow", "Irect", None))
        self.lineEdit_data_Irect.setText(_translate("MainWindow", "0", None))
        self.rx_label_7.setText(_translate("MainWindow", "Icha", None))
        self.lineEdit_data_Icha.setText(_translate("MainWindow", "0", None))
        self.rx_label_5.setText(_translate("MainWindow", "Trxboard", None))
        self.lineEdit_data_Treboard.setText(_translate("MainWindow", "0", None))
        self.rx_label_9.setText(_translate("MainWindow", "State", None))
        self.checkBox_state_overVsens.setText(_translate("MainWindow", "Over Vsens", None))
        self.checkBox_state_underVsens.setText(_translate("MainWindow", "Under Vsens", None))
        self.checkBox_state_overVsensCHA.setText(_translate("MainWindow", "Over VsensCHA", None))
        self.checkBox_state_underVsensCHA.setText(_translate("MainWindow", "Under VsensCHA", None))
        self.checkBox_state_overFsk_dem.setText(_translate("MainWindow", "Over Fsk dem", None))
        self.checkBox_state_underFsk_dem.setText(_translate("MainWindow", "Under Fsk dem", None))
        self.checkBox_state_lowIsens.setText(_translate("MainWindow", "Low Isens", None))
        self.checkBox_state_lowIsensCHA.setText(_translate("MainWindow", "Low IsenseCHA", None))
        self.checkBox_state_overTsens.setText(_translate("MainWindow", "Over Tsens", None))
        self.checkBox_state_underTsens.setText(_translate("MainWindow", "Under Tsens", None))
        self.rx_label_10.setText(_translate("MainWindow", "Threshold", None))
        self.rx_label_11.setText(_translate("MainWindow", "OverVsens", None))
        self.lineEdit_thd_overVsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_12.setText(_translate("MainWindow", "OverVsenCHA", None))
        self.lineEdit_thd_overVsensCHA.setText(_translate("MainWindow", "0", None))
        self.rx_label_13.setText(_translate("MainWindow", "OverFsk_dem", None))
        self.lineEdit_thd_overFsk_dem.setText(_translate("MainWindow", "0", None))
        self.rx_label_14.setText(_translate("MainWindow", "UnderVsens", None))
        self.lineEdit_thd_underVsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_15.setText(_translate("MainWindow", "UnderVsensCHA", None))
        self.lineEdit_thd_underVsensCHA.setText(_translate("MainWindow", "0", None))
        self.rx_label_16.setText(_translate("MainWindow", "UnderFsk_dem", None))
        self.lineEdit_thd_underFsk_dem.setText(_translate("MainWindow", "0", None))
        self.rx_label_20.setText(_translate("MainWindow", "LowIsens", None))
        self.lineEdit_thd_lowIsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_19.setText(_translate("MainWindow", "LowIsensCHA", None))
        self.lineEdit_thd_lowIsensCHA.setText(_translate("MainWindow", "0", None))
        self.rx_label_18.setText(_translate("MainWindow", "OverTsens", None))
        self.lineEdit_thd_overTsens.setText(_translate("MainWindow", "0", None))
        self.rx_label_17.setText(_translate("MainWindow", "UnserTsens", None))
        self.lineEdit_thd_underTsens.setText(_translate("MainWindow", "0", None))

